[workspace]
authors = ["Paul Dutton <jodgey4@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "MojoCNN"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062305,<26"
